### ISSUE TITLE
Add optional permission on Firefox to remove constant notification indicator

### ISSUE THREAD

**Issue by Inclushe** [dimdenGD/cobalt-extension#2]
Any time I navigate to a new page with this extension enabled, I get this annoying indicator in my plugins overflow menu icon. Ultimately, this annoyance keeps me from using the plugin.

<img width="233" alt="Screenshot 2024-01-26 at 2 03 42 PM" src="https://github.com/dimdenGD/cobalt-extension/assets/7546357/e43c9084-0d7b-4c51-a6a5-0e4ce1d06c4c">

When I open the plugins menu, I see that the extension is asking to read data from this page.

<img width="316" alt="Screenshot 2024-01-26 at 2 04 32 PM" src="https://github.com/dimdenGD/cobalt-extension/assets/7546357/322e2875-ee90-4e11-91ab-bc6465a8f95f">

If this helps, I remember encountering this issue with the plugin [yomitan](https://github.com/themoeway/yomitan). To resolve this, they have an [additional optional permission to read data from all pages](https://github.com/themoeway/yomitan/blob/55897b2b29e88ffd0c9140d03b9e74c4a94d98bd/dev/data/manifest-variants.json#L88), which adds this permission to the plugin settings page:

<img width="934" alt="Screenshot 2024-01-26 at 2 10 54 PM" src="https://github.com/dimdenGD/cobalt-extension/assets/7546357/867e64c2-d6b7-4afe-8b5b-6543f1d39fd3">

With it enabled, the notification indicator goes away.

**Comment by dimdenGD** [comment]
I don't use firefox so I can't add this rn, but you're free to make a PR

**Comment by Inclushe** [comment]
#3
