### ISSUE TITLE
basically doesnt work

### ISSUE THREAD

**Issue by yzispx** [dimdenGD/cobalt-extension#9]
i click on the icon of the extension: nothing
i right click and then click on the icon, nothing
using brave

**Comment by dimdenGD** [comment]
Are you using last version (v1.0.6)

**Comment by nottucks** [comment]
I am. It does nothing anymore. No idea why. I'm on Firefox. LMK if there's any info about my browser or the extension I can send you to help with debugging.

**Comment by xammen** [comment]
Have the same issue with Zen Browser

**Comment by dimdenGD** [comment]
Fixed
